import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output = process.env.CAPTURE_DIR || await mkdtemp(path.join(tmpdir(), 'agentpay-capture-'));
await mkdir(output, { recursive: true });
const base = process.env.DEMO_URL || 'http://127.0.0.1:4021/agentpay/';
const browser = await chromium.launch({ headless: true });
const issues = [];
const captions = [];
const stamp = seconds => new Date(Math.round(seconds * 1000)).toISOString().slice(11, 23);
console.log(`Capture directory: ${output}`);
try {
  // Each context is fresh. Recording never borrows the user's browser or wallet.
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, recordVideo: { dir: output, size: { width: 1440, height: 900 } } });
  const page = await context.newPage();
  page.on('pageerror', error => issues.push(error.message));
  const started = Date.now();
  let lastCaption = 0;
  function caption(text) {
    const now = (Date.now() - started) / 1000;
    if (captions.length) captions.at(-1).end = now;
    captions.push({ start: now, end: now + 5, text });
    lastCaption = now;
    console.log(text);
  }
  const hold = milliseconds => page.waitForTimeout(milliseconds);
  const click = action => page.locator(`[data-action="${action}"]`).click();
  await page.goto(`${base}#hire`);
  await page.locator('#budget').waitFor();
  caption('AgentPay: buy the next inference inside an owner-defined policy. Interactive simulation; no new payment.');
  await hold(4000);
  await page.locator('#commission').scrollIntoViewIfNeeded();
  await page.locator('input[value="ask"]').check();
  caption('Set a 5 USDC task budget and require approval. The per-inference ceiling is separate: 0.1 USDC.');
  await hold(4500);
  await page.locator('#commission button[type="submit"]').click();
  await click('baseline');
  assert.equal(await page.locator('#baseline-tests .fail').count(), 1);
  caption('The baseline reproduces a duplicate charge. Save the task before procurement. The capacity trigger is scripted.');
  await hold(6000);
  await click('market');
  await page.locator('.product-window img').waitFor();
  await page.locator('.step-grid').scrollIntoViewIfNeeded();
  caption('Compare real model channels on aiplans.dev. Toolkit is the configured machine-fulfillment route.');
  await hold(6500);
  assert.match(await page.locator('.decision').innerText(), /ask first/i);
  caption('The agent waits for your approval. A policy decision comes before a purchase.');
  await hold(4000);
  await click('approve');
  await click('connect');
  await page.locator('.api-layout').scrollIntoViewIfNeeded();
  await page.getByText('Inspect the SDK request', { exact: true }).click();
  caption('A Toolkit request binds the model and token bounds. This screen replays historical payment evidence.');
  await hold(5500);
  await click('replay');
  await page.locator('.receipt').scrollIntoViewIfNeeded();
  caption('Recorded September 7 request: 17 input plus 256 output tokens. Monad settlement: 0.000001 USDC, not the full ceiling.');
  await page.locator('[data-action="delivery"]:not(:disabled)').waitFor();
  await hold(4500);
  await click('delivery');
  await page.locator('.diff').scrollIntoViewIfNeeded();
  caption('Inspect the retry guard. This teaching fixture is separate from the historical model output.');
  await hold(5000);
  await click('test');
  assert.equal(await page.locator('#acceptance-tests .pass').count(), 3);
  await page.locator('#acceptance-tests').scrollIntoViewIfNeeded();
  caption('Three acceptance tests execute locally in the browser. The owner verifies the deliverable.');
  await hold(5500);
  await click('accept');
  await page.waitForURL('**#overview');
  await page.locator('.overview-map').scrollIntoViewIfNeeded();
  caption('The complete loop: commission, checkpoint, discovery, authorization, settlement, delivery.');
  await hold(4500);
  await page.locator('[data-recap-index="2"]').click();
  await page.locator('#recap-detail').scrollIntoViewIfNeeded();
  await hold(4000);
  await page.locator('[data-recap-index="4"]').click();
  await page.locator('#recap-detail').scrollIntoViewIfNeeded();
  caption('Inspect the historical proof and transaction. No new model call, signature or charge is created by this demo.');
  await hold(5000);
  await page.goto(`${base}#preview`);
  await page.locator('.overview-map').scrollIntoViewIfNeeded();
  caption('Quick preview is available before starting. It grants no purchase permission and records no acceptance.');
  await hold(4500);
  captions.at(-1).end = (Date.now() - started) / 1000;
  assert.ok(captions.at(-1).end > lastCaption);
  const video = page.video();
  await context.close();
  await video.saveAs(path.join(output, 'walkthrough.webm'));
  await video.delete();
  await writeFile(path.join(output, 'captions.vtt'), `WEBVTT\n\n${captions.map(c => `${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n')}`);

  const qa = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const check = await qa.newPage();
  check.on('pageerror', error => issues.push(error.message));
  await check.goto(`${base}#preview`);
  await check.locator('.overview-map').waitFor();
  const state = () => check.evaluate(() => JSON.parse(localStorage.getItem('agentpay.journey.v1')));
  const previewState = await state();
  for (const key of ['hired', 'checkpoint', 'approved', 'paymentDone', 'tested', 'accepted']) assert.equal(previewState[key], false);
  assert.match(await check.locator('.overview-outcome').innerText(), /Not run in preview/);
  await check.reload();
  assert.equal(new URL(check.url()).hash, '#preview');
  await check.locator('[data-recap="play"]').click();
  await check.locator('[data-recap-index="1"][aria-pressed="true"]').waitFor();
  await check.locator('[data-recap="play"]').click();
  await check.locator('[data-recap-index="5"]').click();
  assert.match(await check.locator('#recap-detail').innerText(), /Not run in preview/);
  await check.screenshot({ path: path.join(output, 'preview-desktop.png'), fullPage: true, animations: 'disabled' });
  await check.goto(`${base}#delivery`);
  await check.waitForURL('**#hire');
  await check.locator('input[value="ask"]').check();
  await check.locator('#commission button[type="submit"]').click();
  await check.locator('[data-action="baseline"]').click();
  await check.locator('[data-action="market"]').click();
  await check.locator('[data-action="deny"]').click();
  assert.match(await check.locator('.decision').innerText(), /declined/);
  const blocked = await state();
  await check.goto(`${base}#preview`);
  await check.locator('.overview-map').waitFor();
  assert.deepEqual({ ...await state(), step: blocked.step }, blocked);
  await check.goto(`${base}#connect`);
  await check.waitForURL('**#market');
  await check.locator('[data-action="approve"]').click();
  await check.locator('[data-action="connect"]').click();
  await check.locator('[data-action="replay"]').click();
  await check.locator('[data-action="delivery"]:not(:disabled)').waitFor();
  await check.locator('[data-action="delivery"]').click();
  await check.locator('[data-action="test"]').click();
  await check.locator('[data-action="accept"]').click();
  await check.waitForURL('**#overview');
  await check.reload();
  assert.match(await check.locator('.overview-outcome').innerText(), /Approved by you/);
  await check.locator('[data-recap-index="2"]').click();
  await check.waitForTimeout(450);
  for (const [label, width, height] of [['desktop', 1440, 1000], ['mobile', 375, 812]]) {
    await check.setViewportSize({ width, height });
    assert.equal(await check.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.ok(await check.locator('img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)));
    await check.screenshot({ path: path.join(output, `overview-${label}.png`), fullPage: true, animations: 'disabled' });
  }
  await check.locator('.overview-finish [data-step="delivery"]').click();
  await check.locator('[data-action="try-budget"]').click();
  assert.match(await check.locator('.decision').innerText(), /above your 0.010000 limit/);
  await qa.close();
  assert.deepEqual(issues, []);
  await writeFile(path.join(output, 'verification.json'), JSON.stringify({ checkedAt: new Date().toISOString(), base, passed: ['preview-no-authority', 'preview-refresh', 'preview-denied-policy-preserved', 'preview-play-pause', 'direct-route-gates', 'manual-approval', 'denial', 'historical-replay', 'acceptance', 'accepted-refresh', 'budget-block', 'desktop-mobile-no-overflow', 'images-loaded', 'no-page-errors'], video: 'interactive simulation, not a live paid repair', durationSeconds: captions.at(-1).end }, null, 2));
  console.log('Browser verification passed. Video and captions ready.');
} finally {
  await browser.close();
}
